name: Farmer

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    

jobs:
  plant_grass:
    runs-on: ubuntu-latest
    steps:
      - name: Set up
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GH_TOKEN}}

      - name: Run script
        run: |
          chmod +x ./grass.sh
          ./grass.sh
        shell: bash

      - name: Commit And push
        run: |
          git add .
          git config --global user.email "limjunehyeop@gmail.com"
          git config --global user.name "Jonathan0827"
          git commit -am "🌲🌲🌲"
          git push
